services:
  edge-proxy:
    container_name: edge-proxy
    restart: unless-stopped
    build:
      context: .
      dockerfile: dockerfile
    ports:
      - "80:80"
      - "443:443"
    volumes:
      - certs:/app/certs
      - ./config.yml:/app/config.yml:Z
    extra_hosts:
      - "host.docker.internal:host-gateway"

volumes:
  certs: