http:
  address: ":80"
  redirect_to_https: true

https:
  address: ":443"

rate_limit:
  requests_per_second: 1000
  burst: 3000

tls:
  certs_dir: /app/certs
  domains:
    - info.zelchi.com
    - solar.zelchi.com
    - vtt.zelchi.com
    - foundry.zelchi.com
    - foundry14.zelchi.com
    - foundry13.zelchi.com

dashboard:
  host: info.zelchi.com

fallback:
  host: solar.zelchi.com
  status_code: 302

routes:
  - host: vtt.zelchi.com
    upstream: http://172.17.0.1:9333
  - host: foundry.zelchi.com
    upstream: http://172.17.0.1:30001
  - host: foundry14.zelchi.com
    upstream: http://172.17.0.1:30000
  - host: foundry13.zelchi.com
    upstream: http://172.17.0.1:30001
