http:
  address: ":80"
  redirect_to_https: true

https:
  address: ":443"

tls:
  certs_dir: /app/certs
  domains:
    - vtt.zelchi.com

routes:
  - host: vtt.zelchi.com
    upstream: http://host.docker.internal:9333